
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ../models:/root/.ollama/models  
    pull_policy: always
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 1m30s
      timeout: 5s
      retries: 5
      start_period: 5s

  mariadb-culturaLLM:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: culturaLLM
      MYSQL_USER: user
      MYSQL_PASSWORD: pwd
    ports:
      - "3307:3306" 
    volumes:
      - ./mariadb_data:/var/lib/mysql:Z
      - ./mariadb_init:/docker-entrypoint-initdb.d


  backend:
    build: ./backend
    ports:
      - "8003:8003"
    container_name: backend-cultura
    depends_on:
      - ollama
      - mariadb-culturaLLM
      - nlp_server

    environment:
      SECRET_KEY: 22d008777e8cfff6ba208b4d3299dbc304f6951eda461d5b767c38f6f4b4f8c0
      DB_HOST: mariadb-culturaLLM 
      DB_USER: user
      DB_PASSWORD: pwd
      DB_NAME: culturaLLM
      

  frontend:
     build: ./frontend
     ports:
       - "8001:8001"
     container_name: frontend-cultura
     depends_on:
       - backend 
     environment:
      SECRET_KEY: 22d008777e8cfff6ba208b4d3299dbc304f6951eda461d5b767c38f6f4b4f8c0
     volumes:
      - ./images:/app/images

  nlp_server:
    build: ./nlp
    image: nlp:latest  # Sostituisci con l'immagine Docker corretta
    container_name: nlp_server
    restart: unless-stopped
    env_file:
      - ./nlp/.env
    volumes:
      - ../hugging_face_models:/app/models  
      - models_cache:/models_cache
      - hf_cache:/hf_cache
    ports:
      - "8069:8069"  # Modifica la porta se necessario
    runtime: nvidia  # Assicurati di avere il runtime NVIDIA configurato
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  # Assicurati che il container possa accedere alla GPU

# Volumi nominati per persistenza
# Volumi nominati per persistenza
volumes:
  models_cache:
    driver: local
  hf_cache:
    driver: local

# Network per eventuale espansione futura
