version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ../models:/root/.ollama/models  
    pull_policy: always
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 1m30s
      timeout: 5s
      retries: 5
      start_period: 5s

  mariadb-culturaLLM:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: culturaLLM
      MYSQL_USER: user
      MYSQL_PASSWORD: pwd
    ports:
      - "3307:3306" 
    volumes:
      - ./mariadb_data:/var/lib/mysql:Z
      - ./mariadb_init:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    ports:
      - "8003:8003"
    container_name: backend
    depends_on:
      - ollama
      - mariadb-culturaLLM
      
    environment:
      DB_HOST: mariadb-culturaLLM 
      DB_USER: user
      DB_PASSWORD: pwd
      DB_NAME: culturaLLM
